version: '3'
volumes:  
  postgres_data: {} 
services:  
  app:    
    build:      
      context: .      
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/usr/src/app
      - ./config/master.key:/usr/src/app/config/master.key 
  web:    
    build:      
      context: .      
      dockerfile: ./docker/web/Dockerfile    
    depends_on:      
      - app    
    ports:      
      - 80:80